In [1]:
import pandas as pd
import numpy as np
from numpy.random import default_rng
import matplotlib.pyplot as plt
from sklearn import linear_model
import sqlite3

# Utilizing SQLite through python code

Connect to the db ```lahman2016.sqlite```

In [8]:
con = sqlite3.connect("lahman2016.sqlite")

The **lahman** db is a collection of tables containing Major League Baseball data. We'll use this database to illustrate **SQL** coding. (technically, we're using **sqlite**, which is a different, but very similar, language than **SQL**; for brevity, I will refer to the **sqlite** code as **SQL**)

Here is a list of the tables included in the **lahman** db:

In [9]:
pd.read_sql("SELECT name FROM sqlite_schema WHERE type = 'table'", con)

                   name
0           AllstarFull
1           Appearances
2        AwardsManagers
3         AwardsPlayers
4   AwardsShareManagers
5    AwardsSharePlayers
6               Batting
7           BattingPost
8        CollegePlaying
9              Fielding
10           FieldingOF
11      FieldingOFsplit
12         FieldingPost
13           HallOfFame
14            HomeGames
15             Managers
16         ManagersHalf
17               Master
18                Parks
19             Pitching
20         PitchingPost
21             Salaries
22              Schools
23           SeriesPost
24                Teams
25      TeamsFranchises
26            TeamsHalf

Now let's execute some **SQL** code.

Pull all teams that played in the year 2015 along with all corresponding columns from the Teams table

In [10]:
pd.read_sql("SELECT * FROM Teams WHERE yearID = 2015", con)

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,2015,AL,BAL,BAL,E,3,162,78,81,81,...,134,0.987,Baltimore Orioles,Oriole Park at Camden Yards,2281202,103,104,BAL,BAL,BAL
1,2015,AL,BOS,BOS,E,5,162,81,78,84,...,148,0.984,Boston Red Sox,Fenway Park II,2880694,104,107,BOS,BOS,BOS
2,2015,AL,CHA,CHW,C,4,162,81,76,86,...,159,0.983,Chicago White Sox,U.S. Cellular Field,1755810,92,93,CHW,CHA,CHA
3,2015,AL,CLE,CLE,C,3,161,80,81,80,...,136,0.987,Cleveland Indians,Progressive Field,1388905,106,106,CLE,CLE,CLE
4,2015,AL,DET,DET,C,5,161,81,74,87,...,165,0.986,Detroit Tigers,Comerica Park,2726048,97,98,DET,DET,DET
5,2015,AL,HOU,HOU,W,2,162,81,86,76,...,131,0.986,Houston Astros,Minute Maid Park,2153585,97,99,HOU,HOU,HOU
6,2015,AL,KCA,KCR,C,1,162,81,95,67,...,138,0.985,Kansas City Royals,Kauffman Stadium,2708549,104,103,KCR,KCA,KCA
7,2015,AL,LAA,ANA,W,3,162,81,85,77,...,108,0.984,Los Angeles Angels of Anaheim,Angel Stadium of Anaheim,3012765,94,95,LAA,ANA,ANA
8,2015,AL,MIN,MIN,C,2,162,81,83,79,...,150,0.986,Minnesota Twins,Target Field,2220054,103,104,MIN,MIN,MIN
9,2015,AL,NYA,NYY,E,2,162,81,87,75,...,135,0.985,New York Yankees,Yankee Stadium III,3193795,99,101,NYY,NYA,NYA
10,2015,AL,OAK,OAK,W,5,162,81,68,94,...,154,0.979,Oakland Athletics,O.co Coliseum,1768175,97,98,OAK,OAK,OAK
11,2015,AL,SEA,SEA,W,4,162,81,76,86,...,155,0.985,Seattle Mariners,Safeco Field,2193581,92,94,SEA,SEA,SEA
12,2015,AL,TBA,TBD,E,4,162,84,80,82,...,118,0.984,Tampa Bay Rays,Tropicana Field,1287054,100,102,TBR,TBA,TBA
13,2015,AL,TEX,TEX,W,1,162,81,88,74,...,169,0.981,Texas Rangers,Rangers Ballpark in Arlington,2491875,102,105,TEX,TEX,TEX
14,2015,AL,TOR,TOR,E,1,162,81,93,69,...,145,0.985,Toronto Blue Jays,Rogers Centre,2794891,99,98,TOR,TOR,TOR
15,2015,NL,ARI,ARI,W,3,162,81,79,83,...,146,0.986,Arizona Diamondbacks,Chase Field,2080145,107,106,ARI,ARI,ARI
16,2015,NL,ATL,ATL,E,4,162,81,67,95,...,186,0.985,Atlanta Braves,Turner Field,2001392,97,97,ATL,ATL,ATL
17,2015,NL,CHN,CHC,C,3,162,81,97,65,...,120,0.982,Chicago Cubs,Wrigley Field,2919122,100,100,CHC,CHN,CHN
18,2015,NL,CIN,CIN,C,5,162,81,64,98,...,131,0.985,Cincinnati Reds,Great American Ball Park,2419506,101,101,CIN,CIN,CIN
19,2015,NL,COL,COL,W,5,162,81,68,94,...,171,0.985,Colorado Rockies,Coors Field,2506789,119,118,COL,COL,COL
20,2015,NL,LAN,LAD,W,1,162,81,92,70,...,133,0.988,Los Angeles Dodgers,Dodger Stadium,3764815,101,98,LAD,LAN,LAN
21,2015,NL,MIA,FLA,E,3,162,81,71,91,...,162,0.987,Miami Marlins,Marlins Park,1752235,98,97,MIA,FLO,MIA
22,2015,NL,MIL,MIL,C,4,162,81,68,94,...,164,0.981,Milwaukee Brewers,Miller Park,2542558,101,101,MIL,ML4,MIL
23,2015,NL,NYN,NYM,E,1,162,81,90,72,...,131,0.986,New York Mets,Citi Field,2569753,94,92,NYM,NYN,NYN
24,2015,NL,PHI,PHI,E,5,162,81,63,99,...,145,0.981,Philadelphia Phillies,Citizens Bank Park,1831080,98,98,PHI,PHI,PHI
25,2015,NL,PIT,PIT,C,2,162,81,98,64,...,177,0.981,Pittsburgh Pirates,PNC Park,2498596,99,97,PIT,PIT,PIT
26,2015,NL,SDN,SDP,W,4,162,81,74,88,...,138,0.985,San Diego Padres,Petco Park,2459742,98,97,SDP,SDN,SDN
27,2015,NL,SFN,SFG,W,2,162,81,84,78,...,145,0.987,San Francisco Giants,AT&T Park,3375882,99,97,SFG,SFN,SFN
28,2015,NL,SLN,STL,C,1,162,81,100,62,...,159,0.984,St. Louis Cardinals,Busch Stadium III,3520889,102,101,STL,SLN,SLN
29,2015,NL,WAS,WSN,E,2,162,81,83,79,...,125,0.985,Washington Nationals,Nationals Park,2619843,102,99,WSN,MON,WAS

Let's find all players in the Hall of Fame, the year they were inducted and the category column.

In [11]:
pd.read_sql("SELECT m.nameGiven, m.nameLast, h.yearid, h.category FROM HallOfFame as h INNER JOIN Master as m \
ON h.playerID=m.playerID WHERE h.inducted = 'Y' AND h.category = 'Player'", con)

              nameGiven     nameLast  yearid category
0           Henry Louis        Aaron    1982   Player
1      Grover Cleveland    Alexander    1938   Player
2               Roberto       Alomar    2011   Player
3    Adrian Constantine        Anson    1939   Player
4          Luis Ernesto     Aparicio    1984   Player
..                  ...          ...     ...      ...
245               Early         Wynn    1972   Player
246        Carl Michael  Yastrzemski    1989   Player
247         Denton True        Young    1937   Player
248   Royce Middlebrook       Youngs    1972   Player
249            Robin R.        Yount    1999   Player

[250 rows x 4 columns]

Now I want to see all the managers who managed the Atlanta Braves.

In [12]:
pd.read_sql("SELECT DISTINCT m.nameGiven, m.nameLast FROM Managers as n INNER JOIN Master as m \
ON n.playerID=m.playerID WHERE n.teamID = 'ATL'", con)

           nameGiven   nameLast
0     Robert Randall     Bragan
1      William Clyde  Hitchcock
2     Kenneth Joseph  Silvestri
3      Chalmer Luman     Harris
4          Edwin Lee    Mathews
5       Clyde Edward       King
6   Cornelius Joseph       Ryan
7        James David    Bristol
8      Robert Edward     Turner
9       Vernon Adair     Benson
10        Robert Joe        Cox
11       Joseph Paul      Torre
12      George Edwin       Haas
13       Robert Paul       Wine
14   Charles William     Tanner
15    Russell Eugene      Nixon
16       Fredi Jesus   Gonzalez
17      Brian Gerald    Snitker

I forgot that Ted Turner managed the Braves as some publicity stunt in the 1970's! I can't remember how many games it was or what his record ended up being. Let's take a look with the following code:

In [15]:
pd.read_sql("SELECT * FROM Managers WHERE playerID = (SELECT playerID FROM Master WHERE nameGiven = 'Robert Edward' AND nameLast = 'Turner')", con)

    playerID  yearID teamID lgID  inseason  G  W  L  rank plyrMgr
0  turnete99    1977    ATL   NL         2  1  0  1     6       N

Not a very exciting managerial career, Ted. But at least you can check it off your bucket list!

Let's look at some more accomplished managers.

Return all ```playerID```'s of managers in the Hall of Fame.

In [16]:
hof_managers = pd.read_sql("SELECT DISTINCT m.playerID FROM Managers as m INNER JOIN HallofFame as h \
ON m.playerID=h.playerID WHERE h.inducted = 'Y'", con)
hof_managers

     playerID
0   alstowa01
1   andersp01
2   ansonca01
3   applilu01
4   bancrda01
..        ...
88  willidi02
89  willite01
90  wrighge01
91  wrighha01
92  youngcy01

[93 rows x 1 columns]

Give a count of the above output.

In [17]:
hof_managers.nunique()

playerID    93
dtype: int64

Look at the ```G```, ```W```, and ```L``` records for each season for each manager in the Hall of Fame.

In [18]:
pd.read_sql("SELECT m.playerID, m.G, m.W, m.L FROM Managers as m INNER JOIN HallofFame as h \
ON m.playerID=h.playerID WHERE h.inducted = 'Y'", con)

      playerID    G   W   L
0    alstowa01  154  92  62
1    alstowa01  154  98  55
2    alstowa01  154  93  61
3    alstowa01  154  84  70
4    alstowa01  154  71  83
..         ...  ...  ..  ..
969  wrighha01   46  22  23
970  wrighha01  138  68  69
971  wrighha01  155  87  66
972  wrighha01  133  72  57
973  youngcy01    6   3   3

[974 rows x 4 columns]

Let's look at the career total of the wins and losses for each manager in the Hall of Fame.

In [19]:
pd.read_sql("SELECT m.playerID, SUM(m.W) as W_total, SUM(m.L) as L_total FROM Managers as m INNER JOIN HallofFame as h \
ON m.playerID=h.playerID WHERE h.inducted = 'Y' GROUP BY m.playerID", con)

     playerID  W_total  L_total
0   alstowa01     2040     1613
1   andersp01     2194     1834
2   ansonca01     1296      947
3   applilu01       10       30
4   bancrda01      249      363
..        ...      ...      ...
88  willidi02     1571     1451
89  willite01      273      364
90  wrighge01       59       25
91  wrighha01     1225      885
92  youngcy01        3        3

[93 rows x 3 columns]

Now we'll calculate the career winning percentage of managers in the Hall of Fame and sort by the percentage in descending order.

In [20]:
pd.read_sql("SELECT m.playerID, SUM(m.W) as W_total, SUM(m.L) as L_total, 1.0*SUM(m.W)/(SUM(m.W)+SUM(m.L)) as w_pct \
FROM Managers as m INNER JOIN HallofFame as h ON m.playerID=h.playerID WHERE h.inducted = 'Y' GROUP BY m.playerID ORDER BY w_pct DESC", con)

     playerID  W_total  L_total     w_pct
0   wrighge01       59       25  0.702381
1   spaldal01       78       47  0.624000
2   mccarjo99     2125     1333  0.614517
3   comisch01      840      541  0.608255
4   seleefr99     1284      862  0.598322
..        ...      ...      ...       ...
88  wallabo01       62      154  0.287037
89  bottoji01       21       56  0.272727
90  applilu01       10       30  0.250000
91  wagneho01        1        4  0.200000
92  connoro01        8       37  0.177778

[93 rows x 4 columns]

My guess would be that those managers in the HOF with less than 200 games managed or with a very low `w_pct` were once players and their career as a player got them into the HOF.

Now let's take a look at some pitching HOFers.

Return the total of ```games_started```, ```games```, ```wins```, ```losses```, ```ininnings_per_outs```, ```complete_games```, ```shut_outs```, and ```saves``` for all pitchers in the Hall of Fame.

In [21]:
p_hof = pd.read_sql("SELECT p.playerID, SUM(p.GS) as games_started, SUM(p.G) as games, \
SUM(p.W) as wins, SUM(p.L) as losses, SUM(p.IPOuts) as ipouts, \
SUM(p.CG) as complete_games, SUM(p.SHO) as shut_outs, SUM(p.SV) as saves \
FROM Pitching as p INNER JOIN HallOfFame as h ON p.playerID=h.playerID WHERE h.inducted = 'Y' GROUP BY p.playerID", con)
p_hof

,playerID,games_started,games,wins,losses,ipouts,complete_games,shut_outs,saves
0,alexape01,599,696,373,208,15570,437,90,32
1,ansonca01,0,3,0,1,12,0,0,1
2,becklja01,1,1,0,1,12,0,0,0
3,bendech01,334,459,212,127,9051,255,40,34
4,blylebe01,685,692,287,250,14910,242,60,0
...,...,...,...,...,...,...,...,...,...
96,willivi01,471,513,249,205,11988,388,50,11
97,wrighge01,0,3,0,1,15,0,0,0
98,wrighha01,7,34,4,4,298,0,0,8
99,wynnea01,612,691,300,244,13692,290,49,15
100,youngcy01,815,906,511,316,22064,749,76,17

Again, I would venture to say that those pitchers in the HOF with less than stellar records are probably are not career pitchers - probably fielders and batters who found there way onto the pitching mound a few times in their career.

Let's look at their batting stats. Return the total batting stats for all Hall of Fame pitchers

In [22]:
bat_p_hof = pd.read_sql("SELECT b.playerID, SUM(b.AB) as at_bats, SUM(b.R) as runs, SUM(b.H) as hits, SUM(b.HR) as home_runs, \
SUM(b.RBI) as rbis, SUM(b.BB) as walks, SUM(b.SO) as strike_outs \
FROM Batting as b WHERE b.playerID IN \
(SELECT p.playerID FROM Pitching as p INNER JOIN HallOfFame as h ON p.playerID = h.playerID WHERE h.inducted = 'Y') \
GROUP BY b.playerID", con)
bat_p_hof

      playerID  at_bats  runs  hits  home_runs  rbis  walks  strike_outs
0    alexape01     1810   154   378         11   163     77        276.0
1    ansonca01    10277  1996  3418         97  2076    983        302.0
2    becklja01     9526  1600  2930         86  1575    616        270.0
3    bendech01     1147   102   243          6   116     75         48.0
4    blylebe01      451    19    59          0    25      5        193.0
..         ...      ...   ...   ...        ...   ...    ...          ...
96   willivi01     1493   107   248          1    84     81          8.0
97   wrighge01     2875   665   867         11   330     67        119.0
98   wrighha01      816   183   222          4   111     36         12.0
99    wynnea01     1704   136   365         17   173    141        330.0
100  youngcy01     2960   325   623         18   290     81        150.0

[101 rows x 8 columns]

Yes, those entries with poor pitching stats correspond to some impressive batting stats.

Finally, let's merge the last two tables.

In [23]:
pd.merge(left = p_hof, right = bat_p_hof, how = 'inner', on = 'playerID')

,playerID,games_started,games,wins,losses,ipouts,complete_games,shut_outs,saves,at_bats,runs,hits,home_runs,rbis,walks,strike_outs
0,alexape01,599,696,373,208,15570,437,90,32,1810,154,378,11,163,77,276.0
1,ansonca01,0,3,0,1,12,0,0,1,10277,1996,3418,97,2076,983,302.0
2,becklja01,1,1,0,1,12,0,0,0,9526,1600,2930,86,1575,616,270.0
3,bendech01,334,459,212,127,9051,255,40,34,1147,102,243,6,116,75,48.0
4,blylebe01,685,692,287,250,14910,242,60,0,451,19,59,0,25,5,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,willivi01,471,513,249,205,11988,388,50,11,1493,107,248,1,84,81,8.0
97,wrighge01,0,3,0,1,15,0,0,0,2875,665,867,11,330,67,119.0
98,wrighha01,7,34,4,4,298,0,0,8,816,183,222,4,111,36,12.0
99,wynnea01,612,691,300,244,13692,290,49,15,1704,136,365,17,173,141,330.0
100,youngcy01,815,906,511,316,22064,749,76,17,2960,325,623,18,290,81,150.0

In [ ]:
%%shell
jupyter nbconvert --to html ///content/sqlite_python.ipynb